# Generated by Django 2.0.7 on 2018-07-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('button_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PanelButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_order', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Button')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Panel')),
            ],
            options={
                'ordering': ('button_order',),
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='buttons',
            field=models.ManyToManyField(through='backend.PanelButtons', to='backend.Button'),
        ),
    ]
