# Generated by Django 2.0.7 on 2018-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='panel',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
